# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306b7caeaa2964aef7f72e70af9d291f6813e5c7ab52c490fe872f6dc5e8a1b0fb60e7c10219235dd7347df9cd9d0306690110977b209574b51ea047804dc9b3

test:
  secret_key_base: a4ad91cbaeb1159f6778539836b87afb25658ddf433e12098f9cc3db84300288bbf29b2fc47e82ad7e0ba1daf23ee5657c841c2d83aaa40d6951e3e3371a551b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
